import fs from 'fs'
import clipboardy from 'clipboardy'

const merge = (path: string) => {
    let result = ''
    for (const line of fs.readFileSync(path).toString().split('\n')) {
        if (line.startsWith('#pragma')) {
            continue
        }
        if (line.startsWith('#include')) {
            const left = line.indexOf('"')
            if (left != -1) {
                const right = line.lastIndexOf('"')
                result += merge('../' + line.slice(left + 1, right))
                continue
            }
        }
        result += line + '\n'
    }
    return result
}

const comment = `
// The following code is generated by the merge tool.
// And this is my algorithm competition library link:
// https://github.com/MirionQs/Concrete.
`

clipboardy.writeSync(comment + merge('../main.cpp'))