import os
import sys
import pyperclip

comment = '''
// The following code is generated by the merge tool.
// https://github.com/MirionQs/Concrete
'''

if len(sys.argv) == 1:
    filepath = './main.cpp'
else:
    filepath = sys.argv[1]

visited = []


def merge(filepath: str):
    global visited
    filepath = os.path.normpath(filepath)

    if filepath in visited:
        return ''
    visited.append(filepath)

    result = ''
    with open(filepath) as file:
        for line in file.readlines():
            if line.lstrip().startswith('#pragma'):
                continue
            if line.lstrip().startswith('#include'):
                left = line.find('"')
                if left != -1:
                    right = line.rfind('"')
                    result += merge(os.path.join(os.path.dirname(filepath), line[left + 1: right]))
                    continue
            result += line
    return result + '\n'


pyperclip.copy(comment.lstrip() + merge(filepath))

visited.reverse()
print('Merged files:', visited)
